#!/bin/sh
GROUPNAME="$MARG1"
LABELIP="$1"
LABELNAME="$2"

cp -p $HOME/n2labels $HOME/n2labels.old

cat $HOME/n2labels.old | grep -v ":${LABELIP}$" > $HOME/n2labels
echo "${LABELNAME}:${LABELIP}" >> $HOME/n2labels
rm -f $HOME/n2labels.old
